[FE] 가계부 목록 페이지 목록과 생성 mobX로 상태관리
boostcamp-2020/Project16-C-Account-Book pull request #66
Opened 2020-11-30 15:45 UTC by yoonwoo123

### 📕 Issue Number

#36 #37 
<br/>

### 📙 작업 내역

> 구현 내용 및 작업 했던 내역

- [x] 가계부 목록을 DB에서 fetch하여 화면에 렌더링
- [x] 목록이 나타날 때 애니메이션 효과를 순차적으로 적용(scss)
- [x] 가계부 생성 클릭 시 폼이 나오며 내용을 적고 엔터 시 생성 요청
- [x] 생성 후 목록을 다시 가져와서 렌더링
- [x] 최신 순으로 보여주기 위해 리스트에 reverse() 적용
- [ ] useRef() 를 활용하여 input에 focus 하고 싶었으나 문제 발생..
<br/>

### 멘토님 멘셔닝

@boostcamp-2020/accountbook_mentor
<br/>

2020-11-30 16:48 UTC, msmk530 requested changes
sass는 모듈형태로 사용할지 안할지 통일을 할 때가 된 것 같네요 ㅎㅎ...
전 여러가지 이유로 모듈형태를 사용안하게 되었는데 한번 이야기해보고 통일해보면 좋을 것 같습니다 !!
개인적으로 궁금한점 몇개 리뷰했어요 ㅎㅎ 수고하셨습니다 영우님 !

2020-11-30 16:48 UTC, msmk530 commented on FE/package.json
> +    "mobx-react-lite": "^3.1.6",
mobx-react가 버전 업그레이드 되어서 mobx-react-lite 없애구 mobx-react로 해주었어요 ! 
merge할 때 수정하면 될 것 같네요 ㅎㅎㅎ

2020-11-30 16:48 UTC, msmk530 commented on FE/src/app.tsx
> +import { AccountBookProvider } from './store/AccountBook/account-book.context';
객체형태가 아니라 AccountBookProvider로 받아야 표현이 통일 될 것 같습니다 !!

2020-11-30 16:48 UTC, msmk530 commented on FE/src/store/AccountBook/account-book.hook.ts
> +) =>
여러 store의 hook을 사용하는 컴포넌트가 생길 수 있어서
이름을 useRootData가 아니라 해당 store에서 제공하는 데이터를 이용한 이름으로 변경하면 좋을 것 같습니다 ㅎㅎ
예) useAccountBookData

2020-11-30 16:48 UTC, msmk530 commented on FE/src/store/AccountBook/account-book.store.ts
> +    Create: false,
Create는 메소드인데 아직 만들지 않은 property인가요 !?!?
boolean값이 의도된 값이면 어떤 용도인지 궁금합니다 ㅎㅎ !!

2020-11-30 16:48 UTC, msmk530 commented on FE/src/components/AccountBook/AccountBookList/index.tsx
> +      </div>
useRootData라는 훅을 만든 이유가 observable한 데이터를 구체적으로 설정하고,
해당 값에 대해 반응하도록 useObserver로 observable한 데이터를 감싸서 리턴해주기 때문에
컴포넌트에서는 useObserver로 감싸주지 않아도 될 것 같습니다 ㅎㅎㅎ

2020-11-30 16:48 UTC, msmk530 commented on FE/src/components/AccountBook/AccountBookList/index.tsx
> +  }, []);
getAccountBookList는 네트워크 통신을 하는 함수인데,
컴포넌트 내부에 직접적으로 들어가 있으면 리렌더링시마다 네트워크 통신이 발생할꺼 같아요 ! ...
해당 컴포넌트가 외부요인에 의해 리렌더링 될 여지가 없다면 상관없겠지만, 원치않는 리렌더링 발생시에 네트워크 통신도 발생하게 되면 안좋지 않을까 생각이 드는데... 어떻게 생각하시는지 궁금하네요 ㅠㅠ
getAccountBookList를 통해 얻는 데이터는 전역에 두고, 해당 값을 읽어오는 식으로 하면 데이터가 변하지 않는 경우에는 따로 네트워크 통신이 발생하지 않을 수 있을 것 같은데 같이 이야기해보면 좋을 것 같아요 !!

2020-11-30 17:01 UTC, msmk530 requested changes
궁금한 점 추가하였습니다 ... ㅎㅎ

2020-11-30 17:01 UTC, msmk530 commented on FE/src/components/AccountBook/AccountBookList/index.tsx
> +
useEffect에 의존성배열이 빈 배열이면 
최초로 렌더링 될 때만 fetchAccountBooks를 부르게 되지 않나요 !?!?
가계부 목록 페이지에서 가계부를 추가하거나, 삭제하는등의 행위가 있고나서
변화된 datas를 store에 반영할 수 있는지 궁금합니다 !!

2020-11-30 17:09 UTC, j03y14 approved these changes
수고하셨습니다 영우님!

mobx 상태관리가 쉽지 않네요ㅠㅠ

2020-11-30 17:09 UTC, j03y14 commented on FE/src/components/AccountBook/AccountBookControl/index.tsx
> +import { PlusCircleIcon } from '@primer/octicons-react';
이건 뭔가요? 아이콘 같은데 모듈이 따로 있나요?👀

2020-11-30 17:09 UTC, j03y14 commented on FE/src/store/AccountBook/account-book.hook.ts
> +) =>
민섭님이 링크해주신 블로그 보니까 `useStoreData()`를 여러곳에서 재사용 할 수 있게 만든 것 같아서 지금 민섭님이 하신 코드에서 `useStoreData()`가 많은데 이걸 한 파일로 합쳐도 될 것 같아요

2020-11-30 17:09 UTC, j03y14 commented on FE/src/components/AccountBook/AccountBookList/index.tsx
> +        <div className={styles.acbook}>
혹시 key값을 넣어주라고 하지 않나요?

2020-11-30 17:09 UTC, j03y14 commented on FE/src/components/AccountBook/AccountBookList/index.tsx
> +  };
이렇게 하면 하나를 추가할 때마다 전체 accountbook을 다시 가져와야될 것 같아요!

그리고 이렇게 한다고 해도 혹시 `postFetch` 요청을 한 뒤에 await를 하지 않고 다음으로 넘어가서 `fetchAccountBooks`에서 추가하려고 한 게 아직 추가되지 않은 상태의 가계부가 반환될 가능성도 있는 것 같아요!

2020-11-30 17:13 UTC, msmk530 commented on FE/src/store/AccountBook/account-book.hook.ts
> +) =>
넵넵  useStoreData가 재사용 가능하도록 설계되긴 했는데 ... 
하나의 파일로 두고 사용하려면 인자로 context값도 넘겨줘야하고, 그걸 넘기는 쪽이 컴포넌트 쪽이라서
컴포넌트쪽에 코드를 추가하는 거 보다 그냥 파일을 따로두고 사용하는 식으로 하긴 했습니다 ㅠㅠ 이야기 해보면 좋을 것 같네요 ㅎㅎ

2020-12-01 00:44 UTC, hi0826 approved these changes
👍  수고하셨습니다. 
프런트는 갈 길이 너무 머네요

2020-12-01 01:00 UTC, yoonwoo123 commented on FE/package.json
> +    "mobx-react-lite": "^3.1.6",
아 전부 같은 기능까지 제공하는건가요? 감사합니다.

2020-12-01 01:02 UTC, yoonwoo123 commented on FE/src/store/AccountBook/account-book.store.ts
> +    Create: false,
가계부 생성 폼을 화면에 띄울지 말지 결정해주는 boolean 값입니다. ㅎㅎ

2020-12-01 01:05 UTC, yoonwoo123 commented on FE/src/components/AccountBook/AccountBookControl/index.tsx
> +import { PlusCircleIcon } from '@primer/octicons-react';
네 저번 3주 프로젝트때 팀원분이 쓰셨던 사이트인데 npm 설치 하면 아이콘을 불러오기 편리합니다.

2020-12-01 01:05 UTC, yoonwoo123 commented on FE/src/components/AccountBook/AccountBookList/index.tsx
> +        <div className={styles.acbook}>
맞습니다 ㅋㅋ 키값 warning이 뜨는데 딱히 넣어줄 값이 없어서 _id 값이라도 넣어줘야 하나 고민중입니다.

2020-12-02 09:13 UTC, msmk530 approved these changes

2020-12-02 09:13 UTC, merged